### ISSUE TITLE
Warning with elixir 1.18

### ISSUE THREAD

**Issue by epinault** [elixirs/faker#579]
I am on OTP 27.2, elixir 1.18.0 and I see this

```
warning: using map.field notation (without parentheses) to invoke function Faker.Random.Elixir.random_uniform() is deprecated, you must add parentheses instead: remote.function()
  (faker 0.18.0) lib/faker.ex:109: Faker.random_uniform/0
  (faker 0.18.0) lib/faker/address.ex:188: Faker.Address.latitude/0
  test/my_app/admin/location_test.exs:13: anonymous fn/2 in :elixir_compiler_3.__MODULE__/1
  (ex_unit 1.18.0) lib/ex_unit/callbacks.ex:787: ExUnit.Callbacks.__describe__/4
  test/my_app/admin/location_test.exs:8: (module)
  (elixir 1.18.0) src/elixir_compiler.erl:77: :elixir_compiler.dispatch/4
  (elixir 1.18.0) src/elixir_compiler.erl:52: :elixir_compiler.compile/4
  (elixir 1.18.0) src/elixir_module.erl:454: :elixir_module.eval_form/7
  (elixir 1.18.0) src/elixir_module.erl:156: :elixir_module.compile/7
  (elixir 1.18.0) src/elixir_compiler.erl:38: :elixir_compiler.maybe_fast_compile/2
  (elixir 1.18.0) src/elixir_lexical.erl:13: :elixir_lexical.run/3
  (elixir 1.18.0) src/elixir_compiler.erl:17: :elixir_compiler.quoted/3
  (elixir 1.18.0) lib/kernel/parallel_compiler.ex:562: Kernel.ParallelCompiler.require_file/2
  (elixir 1.18.0) lib/kernel/parallel_compiler.ex:445: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/
```

**Comment by matt-savvy** [comment]
Looks like that's the same as https://github.com/elixirs/faker/issues/569. Been getting this warning since Elixir 1.17

**Comment by epinault** [comment]
@matt-savvy yea I guess . then wonder when it will get fixed :/

**Comment by epinault** [comment]
@anthonator @tobyhinloopen @vbrazo  Do you need help here? I see quite a few PR piling. Do you need more maintainers?

**Comment by tobyhinloopen** [comment]
I have been summoned! 

It has been a while since I looked at this repo. I think it's wise that the maintainers (that's me and some others) schedule a moment where we discuss how we can get through the open PRs, and what to do with future PRs.

**Comment by igas** [comment]
Thanks @tobyhinloopen, it's been awhile. I think we discussed that you don't work with elixir day to day and don't have time. I've joined Alembic recently, I'll discuss it with the team there, I'm sure I'll be able to bring more maintainers. I started to cleanup PRs. Should cut release soon.

**Comment by arcanemachine** [comment]
Hello @igas, I'd be happy to contribute to these efforts if you need any help.

EDIT: If anyone just needs a Hex package that fixes the warnings, there is https://hex.pm/packages/faker/0.19.0-alpha.1

**Comment by epinault** [comment]
@igas if you don t have time, some of us are happy to help? maybe give more maintainers access? also the Beam community would like be happy to help with that (which I am part of) or my company as well participate
